### ISSUE TITLE
Bucket hats on mobs sometimes turn invisible

### ISSUE THREAD

**Issue by calloatti** [JamiesWhiteShirt/bucket-hat#1]
MC 1.14.4
bucket-hat-1.0.0.jar

https://youtu.be/QQwfgC20xXo

**Comment by JamiesWhiteShirt** [comment]
Based on the video I suspect it has something to do with which other entities are on the screen. You might also notice artifacts on the XP orb at 43 seconds into the video. I haven't tested it for myself, but Illuminations is a likely suspect right now.

**Comment by calloatti** [comment]
Yes, there were quite a few fireflies around. And I did notice the xp orb artifact. That could be the Windows 10 capture software too maybe?

**Comment by JamiesWhiteShirt** [comment]
The XP orb looked more like it didn't have alpha testing enabled so it rendered otherwise transparent pixels as black. I think _something_ is leaking GL state but I'm not 100% sure what. I have a hunch it's an issue with Illuminations disabling alpha testing [here](https://github.com/Ladysnake/Illuminations/blob/7c9fd5901db9efad43404b2bd80f08e7a35a1668/src/main/java/ladysnake/illuminations/client/renders/entities/FireflyRender.java#L98).

**Comment by calloatti** [comment]
Saw the exact same thing happening with a Vanilla Iron Helmet, so it must be another mod, will try to track it down.

**Comment by calloatti** [comment]
Found it: https://www.curseforge.com/minecraft/mc-mods/first-person-model
